### ISSUE TITLE
\overline doesn't work correctly 

### ISSUE THREAD

**Issue by Kezzya** [fast-reflexes/better-react-mathjax#15]
\overline has to be above a letter.

**Comment by fast-reflexes** [comment]
Hi!

I'm not sure if I'm missing something but it seems to work fine for me:

```js
      <MathJax>{"$\\overline{R}$"}</MathJax>
      <MathJax>{"$\\overline{O}$"}</MathJax>
      <MathJax>{"$\\overline{ABC}$"}</MathJax>
      <MathJax>{"$\\overline{V}$"}</MathJax>
```
<img width="54" alt="Screenshot 2022-05-26 at 21 08 24" src="https://user-images.githubusercontent.com/2438128/170559552-af6b3b0b-8b2e-44a8-83e5-4a31fd23279d.png">

Check out this sandbox: https://codesandbox.io/s/user-example-15-euztn9

What are you trying to accomplish and in what way doesn't it work?

**Comment by fast-reflexes** [comment]
That's interesting ... So first of all, I tried doing this in a pure MathJax environment and the result is the same so the problem, if any (not sure what the contract from MathJax's side on results with other fonts is), lies in MathJax and not better-react-mathjax. However, if you switch the catch-all `*` for a a more limited scope, such as a class, then it works:

https://codesandbox.io/s/user-example-15-b-ueu8wq

I don't see a huge difference in the fonts but I see SOME difference in size so I guess the style is applied, how does it work for you? Perhaps there's some system font I don't have installed that is being used (even though I DO replicate the ugly behaviour you're talking about when using the `*` scope),
