### ISSUE TITLE
Instructions on adding library to project

### ISSUE THREAD

**Issue by raiyansayeed** [fast-reflexes/better-react-mathjax#2]
First off, amazing work! Thank you for making this awesome library.

Would it be possible to include instructions in the README on adding the library to your project (could be as simple as adding `npm i better-react-mathjax` and the yarn equivalent)?

**Comment by fast-reflexes** [comment]
Hi there! Thanks a lot for your kind comments, for using it and for contributing here! 🎈 🥳 

Good suggestion! I added a short section on this. Will be in release 1.0.3 which will come soon!

**Comment by fast-reflexes** [comment]
Added in v. 1.0.3
