### ISSUE TITLE
Display chemical formulae using the mhchem extension?

### ISSUE THREAD

**Issue by austinbooth** [fast-reflexes/better-react-mathjax#25]
Hi, is it possible to use the [mhchem extension](https://docs.mathjax.org/en/latest/input/tex/extensions/mhchem.html?highlight=chemical#mhchem) to display chemical formulae etc?

**Comment by fast-reflexes** [comment]
Thanks for your question!

Everything that can be done in MathJax can be done with `better-react-mathjax`. MathJax supports the math extension of MathJax and a subset of other features / packages. Nonetheless, everything that can be done in Latex can NOT be done in MathJax.

However, it looks like the `mhchem` extension is supported (like you linked to yourself): https://docs.mathjax.org/en/latest/input/tex/extensions/mhchem.html

I don't know if this extension in Latex supports more macros than are available in MathJax, but at least some of them are. Note that Latex extensions that are available in MathJax are entirely rewritten from their Latex counterparts. 

Here is a sandbox: https://codesandbox.io/s/better-react-mathjax-basic-example-latex-forked-hxcekd
I just grabbed a `mhchem` expression from https://docs.moodle.org/400/en/Chemistry_notation_using_mhchem.

Hope that's what you want!

**Comment by austinbooth** [comment]
Yes that's perfect, thanks!
