### ISSUE TITLE
How to catch typographical errors

### ISSUE THREAD

**Issue by KanChaiShaoXia** [fast-reflexes/better-react-mathjax#27]
I want to get error information when there is a typographical error. How can I get it

![image](https://user-images.githubusercontent.com/34398562/189814026-fa8e6a76-fb94-405d-9232-3c5c3f9c5197.png)

![image](https://user-images.githubusercontent.com/34398562/189813820-26e92fed-b7c1-48c3-b147-460589e395d7.png)

**Comment by fast-reflexes** [comment]
Perhaps this information can be displayed in a better way than it is today... could you give me an example of input that you think should trigger an error in a visible way?

**Comment by KanChaiShaoXia** [comment]
I found what I wanted
[formaterror](https://docs.mathjax.org/en/latest/options/input/tex.html#tex-formaterror)
this issues was solved
