### ISSUE TITLE
<msqrt> Sometimes not display completely

### ISSUE THREAD

**Issue by kalavaso** [fast-reflexes/better-react-mathjax#31]
Hi
When I try to display some formulas that have an great equation with integrals or divisions, sometimes the √ symbol is displayed incomplete, depend of the size of the window and the zoom.
Thk!
I use this versions
-------------------------------
"react": "^17.0.2"
"better-react-mathjax": "^2.0.1"
-------------------------------
Some pictures to see the problem

This zoomed in at 80%
![image](https://user-images.githubusercontent.com/40798649/199842096-9547526a-0da5-45ff-8c69-793b48031022.png)

This zoomed in at 100%
![image](https://user-images.githubusercontent.com/40798649/199842229-653ac7cb-fd6b-4695-bd6f-ae6dbbafc813.png)

The code: 
[sqrt MathJax.txt](https://github.com/fast-reflexes/better-react-mathjax/files/9933304/sqrt.MathJax.txt)

**Comment by fast-reflexes** [comment]
Hi there!

Could you give me the specifics of the context here? Full MathJax config, which version of MathJax you use, font size of the MathJax content etcetera? I think this is a problem in MathJax itself and thus something that you have to file a ticket about in the [MathJax repo](https://github.com/mathjax/MathJax).

Here is a [sandbox](https://codesandbox.io/s/better-react-mathjax-31-5keqz6) with just pure MathJax and your formula where I can replicate what you're seeing at some zoom levels in Chrome (25%, 400%, 500%). So perhaps if you give me some surrounding context, I can replicate it at your zoom levels too using MathJax only in which case `better-react-mathjax` is not to blame.

Generally, `better-react-mathjax` doesn't do much more than just accomodate the use of MathJax in React so intuitively, such a problem as the above is with very high probability the result of the MathJax library itself.

**Comment by pkra** [comment]
It's likely a browser bugs around zooming & repainting, see https://github.com/mathjax/MathJax/issues?q=is%3Aissue+zoom for many discussions.

**Comment by fast-reflexes** [comment]
Thanks for chiming in @pkra ! :)

**Comment by pkra** [comment]
> Thanks for chiming in @pkra ! :)

Thank you for maintaining this project!

**Comment by fast-reflexes** [comment]
Please reopen if you feel that there is anything more to discuss.. As said, I don't think the problem is in this library but instead in MathJax or in browsers themselves.
