### ISSUE TITLE
Not able to render complexed Sylvester equation

### ISSUE THREAD

**Issue by kherP** [fast-reflexes/better-react-mathjax#32]
Hi, i tried to use this library to render 
```LaTex
A^{m\times m}X^{m\times n}+X^{m\times n}B^{n\times n}=C^{m\times n} \\\left[\begin{matrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{matrix} \right] \left[\begin{matrix} x_{11}  \\ x_{21}  \end{matrix}\right] + \left[\begin{matrix} x_{11} \\ x_{21} \end{matrix}\right]  b_{11}     = \left[\begin{matrix} c_{11} \\ c_{22} \end{matrix} \right] 
```

but it's not rendered properly:
![image](https://user-images.githubusercontent.com/12553063/199918753-1a7d3087-bbd1-4655-8bcf-cb0e6ab9d4e4.png)

I tried using the following code:
```jsx
<MathJaxContext>
      <h2>Basic MathJax example with Latex</h2>
      <MathJax>{`A^{m\\times m}X^{m\\times n}+X^{m\\times n}B^{n\\times n}=C^{m\\times n} \\\\\\left[\\begin{matrix}
  a_{11} & a_{12} \\\\
  a_{21} & a_{22}
  \\end{matrix} \\right] \\left[\\begin{matrix}
  x_{11}  \\\\
  x_{21} 
  \\end{matrix}\\right] + \\left[\\begin{matrix}
  x_{11} \\\\
  x_{21} \\end{matrix}\\right] 
  b_{11}  
    = \\left[\\begin{matrix} c_{11} \\\\ c_{22} \\end{matrix} \\right]`}</MathJax>
    </MathJaxContext>
 ```
 
 but in MathJax preview, i can see it rendered perfectly. The only difference is that i added dollar sign for prefix and suffix for the mathjax demo. I tried to do the same in better-react-mathjax but It didn't work.
 
![image](https://user-images.githubusercontent.com/12553063/199922506-ebd3208e-5a6e-4e65-9a02-2a83f5d30387.png)

**Comment by fast-reflexes** [comment]
Hi there!

You have to use the MathJax delimiters set out in the configuration. If you give no configuration, the [default applies](https://docs.mathjax.org/en/latest/web/configuration.html#configuring-mathjax) which means `\(` and `\)` are used for inline math. If you supply them, the code works as expected. Perhaps the other library that you mention takes care of this for you but `better-react-mathjax` aims at being just a wrapper around MathJax that doesn't interfere with regular MathJax operation, therefore you can pick your own delimiters in the configuration and you also have to add the delimiters in code. Please check examples in the [documentation](https://github.com/fast-reflexes/better-react-mathjax#examples).

[Sandbox with working samples using two different delimiters](https://codesandbox.io/s/better-react-mathjax-32-mfzpg9)

Please close the ticket if this solves your problem :)

**Comment by kherP** [comment]
it works, thank you!
