### ISSUE TITLE
How to align mathjax to the left? 

### ISSUE THREAD

**Issue by nioclass** [fast-reflexes/better-react-mathjax#36]
I am unable ot figure out how to set the mathjax equation aligned to the left instead of being centre aligned. Any info would be helpful.

**Comment by tanmayaBiswalOdiware** [comment]
Hello there, I happen to know one solution atleast. 

![image](https://user-images.githubusercontent.com/111624693/204081612-5795eaad-3a43-4198-88ba-7308d4a3dd08.png)

If I had to figure out the solution, I would just go for the CSS property here. Just set it to 'left' and you are gold. Perhaps there is a more official API, but I have not seen that yet.

**Comment by fast-reflexes** [comment]
You can impact this on two basic levels:

* In Latex, AsciiMath and MathML, there is the notion of display math and inline math (https://github.com/fast-reflexes/better-react-mathjax#display-math-and-inline-math). The first is displayed centered in its container and the latter inline as any text. You would want to use inline math for your use-case.
* The `MathJax` element can either be inline or block. Add the prop `inline` to it and then the wrapper element will be inline too.

The rest is just a matter of where you place your `MathJax` element like any HTML.

**Comment by fast-reflexes** [comment]
Will close this one, feel free to open it if you feel something is wrong.
