### ISSUE TITLE
Not working correctly with dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by dekahanmaa** [fast-reflexes/better-react-mathjax#37]
Thank you for the great Library.

I am having problems with formulas not being replaced correctly in code using dangerouslySetInnerHTML.

The code is as follows.

```typescript
<MathJaxContext>
...
  <MathJax>
    <Box dangerouslySetInnerHTML={{ _html=html_from_api_response }}>
    </Box>
  </MathJax>
...
</MathJaxContext>
```
It works fine when I try it without dangerouslySetInnerHTML.

I would appreciate your help.

**Comment by fast-reflexes** [comment]
Hi there and thanks!

So, is this data present already when you render the first time or does it come in later? If the data comes in later, you have to set `dynamic` flag on the `MathJax` component, otherwise it will not typeset more than once.

**Comment by dekahanmaa** [comment]
I set the MathJax component to dynamic and now it works correctly!
Thank you!
