### ISSUE TITLE
Not able to use MathJax v2

### ISSUE THREAD

**Issue by petermarks12** [fast-reflexes/better-react-mathjax#39]
I have an equation that is not wrapping on mobile devices and resulting in horizontal scroll bar.  I have tried to look for possible solution and but most of them referring to use Mathjax v2.  I tried to do the same on Next JS app and constantly getting this error.  Code and error are given below. 

**Note**:  I am not using any other MathJax context in my entire app.  There is only 1 context defined in the _app.js

` <MathJaxContext version={2}>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </MathJaxContext>`

> Error: Cannot use MathJax versions 2 and 3 simultaneously in the same app due to how MathJax is set up in the browser; either you have multiple MathJaxContexts with different versions or you have mounted and unmounted MathJaxContexts with different versions. Please stick with one version of MathJax in your app. File an issue in the project Github page if you need this feature.

**Comment by pkra** [comment]
Not immediately helpful but just fyi: MathJax v4 will add support for linebreaks again, see https://github.com/mathjax/MathJax-src/releases/tag/4.0.0-alpha.1#linebreaking.

**Comment by fast-reflexes** [comment]
Never encountered this before when you only have one `MathJaxContext` so the obvious questions are whether you are importing some other library that uses `better-react-mathjax` as well or if you have forgotten something? That message is literally only displayed when the `MathJaxContext` encounters an existing `MathJaxBaseContext` with a version different than the one you have explicitly set. Try to simulate the problem in a codesandbox and I can have a look :)

**Comment by petermarks12** [comment]
I have checked it multiple times, but seems there is no other MathJax context. I will try to simulate the problem in codesandbox.   So far for the wrapping issue, i have found the following solution and it seems to be working.

```
mjx-math.MJX-TEX {
  white-space: normal !important;
  line-height: 0.5 !important;
}
```

**Comment by elias-at-levels** [comment]
Try to comment out code, piece by piece until you ONLY have the `MathJaxContext` left in the app and see when the error disappears.

**Comment by fast-reflexes** [comment]
Try to comment out code, piece by piece until you ONLY have the MathJaxContext left in the app and see when the error disappears.

**Comment by fast-reflexes** [comment]
Feel free to reopen if you can provide more detail. For now, it's not possible to trouble-shoot.
