### ISSUE TITLE
MathJax not rendering in CRA optimized production build

### ISSUE THREAD

**Issue by mark-wiemer** [fast-reflexes/better-react-mathjax#42]
1. Clone https://github.com/mark-wiemer/better-react-mathjax-bug
2. `npm start` and change the input to `1+2`: you'll see the MathJax render correctly
3. `npm run build && serve -s build`, change the input

Expected: MathJax renders correctly

Actual: MathJax just renders as plaintext

Notes: Debugging via sources tab shows the same value is stored for the `latex` variable in `App.tsx`. Without special text, the `React Components` tab provided by [React Developer Tools Chromium extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) shows the same children to the component.

However, when rendering a fraction, the prod build shows a single backslash provided as a child `\frac{1}{2}` instead of `\\frac{1}{2}`, which is how the `npm start` build works.

## `npm start` build:
![image](https://user-images.githubusercontent.com/7833360/229670719-d46659ff-23bd-43a2-9dd7-db20819c1b43.png)

## Optimized production build:

One backslash:
![image](https://user-images.githubusercontent.com/7833360/229670768-9045e0d3-00c5-4d04-9ea5-46f7f0a92f8c.png)

Two backslashes:
![image](https://user-images.githubusercontent.com/7833360/229670826-9a5c423a-f336-47cb-825b-8041c379dde1.png)

**Comment by fast-reflexes** [comment]
Hi there!

Thanks for the question, before I even start digging into this, did you add the `dynamic` property to the `MathJax` component (as you should when the content will change after initial rendering)[https://github.com/fast-reflexes/better-react-mathjax#dynamic-boolean--undefined]? :)

**Comment by mercicle** [comment]
Thanks for submitting this issue! `dynamic={true}` This fixed my Heroku production bug as well. Whew!
