### ISSUE TITLE
Typescript error TS1209: Ambient const enums are not allowed when the '--isolatedModules' flag is provided

### ISSUE THREAD

**Issue by selimbat** [fast-reflexes/better-react-mathjax#45]
When running a type-check, I have the aforementioned error with the `DIRECTION` enum in `FontData.d.ts`.
The error is resolved by changing the declaration from `declare const enum` to `declare enum`
My TypeScript version is 4.7.4, with the isolatedModules flag activated.

**Comment by fast-reflexes** [comment]
Hi there!

Thanks for reporting! Types are exported directly from the `mathjax-full` package so all type errors should be addressed directly to https://github.com/mathjax/MathJax

**Comment by fast-reflexes** [comment]
I'm closing this, feel free to reopen if you think this is wrong! 🎈
