### ISSUE TITLE
Not working with serve -s build

### ISSUE THREAD

**Issue by atigm** [fast-reflexes/better-react-mathjax#51]
On my Localhost it's working fine, but when I deploy on AWS Amlify, It's not working, there is not rendering.
On my localhost I have like that : `<mjx-container class="MathJax ....`
But on  production (AWS Amplify), I don't have `<mjx-container class="MathJax ....`

Amplify use these commands : 
```
npm install -g serve 
serve -s build
```
(https://cra.link/deployment)

I use React 18 with Typescript.

**Comment by fast-reflexes** [comment]
Can you replicate this locally with `serve -s build`?

**Comment by atigm** [comment]
Thank you @fast-reflexes 
I'm sending you the link to the repo that contains the build content file.

**Comment by atigm** [comment]
I realized that the library doesn't work with 'npm run build'. It only works in development mode with 'npm start'.

**Comment by fast-reflexes** [comment]
Nah, I have an app which is built and served from Amazon S3 which works great so that's not the problem. I will have a look in the weekend if I have time :)

**Comment by atigm** [comment]
@fast-reflexes Ok, Thank you

**Comment by atigm** [comment]
I have conducted several tests locally and identified a specific scenario where an issue occurs. 
In the case `npm run build`, if the message to be displayed is received via WebSocket, there is a problem. 
Otherwise, everything works fine in all other scenarios (such as `npm start` with WebSocket, etc.).

**Comment by atigm** [comment]
It's just a mistake on my part; I forgot to add `dynamic`:
`<MathJax dynamic>`

**Comment by fast-reflexes** [comment]
Yeah, local development uses `dynamic` automatically to work correctly with hot reload, when deploying in production you have to make sure to add this explicitly for typesetting updated content :)
