### ISSUE TITLE
How to copy to clipboard

### ISSUE THREAD

**Issue by atigm** [fast-reflexes/better-react-mathjax#52]
Hi,

I'm using React/TypeScript. Can I use this repository to copy formatted text to the clipboard?
I want to copy all text, not just the math expressions. 
Alternatively, can I use it directly with CopyToClipboard?

for example 
<img width="644" alt="mathjax" src="https://github.com/fast-reflexes/better-react-mathjax/assets/32271996/06900104-d854-414e-8a97-1619b2e7c095">

Thank you

**Comment by fast-reflexes** [comment]
This is advanced use of MathJax and not necessarily something I can help out with within the scope of this library :)

If I just mark some text with MathJax expressions and copy it, it works, but some of the expressions do not even have equivalents in regular text .. for example the limit or the square root, I don't know what ASCII character you would use for those... So some of the copied text will contain odd characters.

You could also store the unprocessed text in a variable and use regular Javascript event listeners and listen for CTRL-C and then use the Javascript Clipboard API (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard) to manually copy it to the clipboard. You can also preprocess the text in any way you would like to remove MathJax delimiters and such...

Good luck!

**Comment by atigm** [comment]
Alright, thank you.
