### ISSUE TITLE
tex2svg is not supported

### ISSUE THREAD

**Issue by hensuninnovation** [fast-reflexes/better-react-mathjax#54]
https://github.com/fast-reflexes/better-react-mathjax/blob/48f6ad4677a6f36e704e3747d0e0a89500352cd7/src/MathJaxContext/MathJaxContext.tsx#L62

Thank for sharing this library! We noticed that it only supports tex2chtml and other options in the TypesettingFunction setting don't take effect because the MathJax library url is hard coded.

**Comment by fast-reflexes** [comment]
You're welcome!

You can add your own source if you want: https://github.com/fast-reflexes/better-react-mathjax?tab=readme-ov-file#src-string--undefined

There was just another thread about `tex2svg`, check it out: https://github.com/fast-reflexes/better-react-mathjax/issues/53

All in all, it works as it should, you just need to import the right source :)

**Comment by fast-reflexes** [comment]
I will consider this solved, please feel free to reopen if you think not.
