### ISSUE TITLE
MathJax.js:1 Uncaught (in promise) Error: Typesetting failed: Cannot read properties of null (reading 'contains')

### ISSUE THREAD

**Issue by Omer1Yuval1** [fast-reflexes/better-react-mathjax#57]
This error seems to happen when the `key` attribute of the `<MathJax>` tag contains certain characters.

**Comment by fast-reflexes** [comment]
This is impossible to troubleshoot without a reproducible sample showing where this error occurs, please provide one or close the ticket.

**Comment by fast-reflexes** [comment]
Can you create a reproducible sample?

**Comment by fast-reflexes** [comment]
Closing since not enough to work with, feel free to reopen when you can provide more info.
