### ISSUE TITLE
Unit vector sign does not work(shows) properly

### ISSUE THREAD

**Issue by CoderKawsar** [fast-reflexes/better-react-mathjax#69]
\hat{i}
\widehat{i}
\overline{i}
\tilde{i}

All of these unit vector signs do not show vector signs correctly. All of these signs break in with the letter tittle(.)

**Comment by fast-reflexes** [comment]
Looks ok to me ...

      <div style={{ textAlign: "center" }}>
        <MathJax>
          {"$$\\hat{i}$$"}
          {"$$\\widehat{i}$$"}
          {"$$\\overline{i}$$"}
          {"$$\\tilde{i}$$"}
          {"\\(\\hat{i}\\)"}
          {"\\(\\widehat{i}\\)"}
          {"\\(\\overline{i}\\)"}
          {"\\(\\tilde{i}\\)"}
        </MathJax>
      </div>

<img width="95" alt="Skärmavbild 2024-10-02 kl  19 50 21" src="https://github.com/user-attachments/assets/bec022de-15c4-4e2a-9296-d8a493d1296e">

Could you specify what's wrong and give me both a picture of what it looks like and provide the code?

**Comment by fast-reflexes** [comment]
@CoderKawsar please provide further input or I can't help you out.

**Comment by CoderKawsar** [comment]
I'm sorry, man. It's working perfectly now. The font was causing the problem. Changing to a math font resolves the problem.
