### ISSUE TITLE
Facing Typesetting failed issue on my code help me out to solve it.

### ISSUE THREAD

**Issue by rahul-lg424** [fast-reflexes/better-react-mathjax#71]
hi my name is rahul ... currently i am using this libary and i am facing an issue Typesetting failed: actually i made a faq item component where i want to show formulas and also text into that component with accordian ... here is the code bellow .. can you please help me out to solve the issue 
"use client";
import { MathJax, MathJaxContext } from "better-react-mathjax";
import { useEffect, useRef, useState } from "react";
import { TfiArrowCircleRight } from "react-icons/tfi";

const FaqItem = ({ faqs }) => {
  const [openIndex, setOpenIndex] = useState(null);
  const contentRefs = useRef([]);

  const updateMaxHeight = () => {
    contentRefs.current.forEach((contentRef, index) => {
      if (contentRef) {
        contentRef.style.maxHeight =
          index === openIndex ? `${contentRef.scrollHeight}px` : "0px";
      }
    });
  };

  const isMathJaxContent = (content) => {
    const mathRegex = /\$\$[\s\S]*?\$\$|\\\(|\\\[|\\\)/;
    return mathRegex.test(content);
  };

  const forceMathJaxUpdate = () => {
    if (window.MathJax) {
      window.MathJax.typesetPromise()
        .then(() => {
          updateMaxHeight();
        })
        .catch((err) => console.log("Typesetting failed: ", err));
    }
  };

  useEffect(() => {
    if (openIndex !== null) {
      setTimeout(forceMathJaxUpdate, 100);
    } else {
      updateMaxHeight();
    }
  }, [openIndex]);

  if (!Array.isArray(faqs)) {
    console.error("Invalid prop 'faqs': expected an array.");
    return null;
  }

  return (
    <MathJaxContext>
      <div className="flex flex-col gap-6 w-full text-center manrope-fonts">
        {faqs.map((item, index) => (
          <div
            key={index}
            className={`flex flex-col items-center justify-center text-center gap-2 p-3 md:p-4 cursor-pointer ${
              openIndex === index
                ? "transition-all duration-500 bg-white shadow-card-shadow rounded-lg"
                : "border-b border-gray-400"
            }`}
            onClick={(e) => {
              e.stopPropagation();
              setOpenIndex(openIndex === index ? null : index);
            }}
          >
            <div className="flex justify-between items-center w-full text-left cursor-pointer">
              <h3
                dangerouslySetInnerHTML={{ __html: item.question }}
                className={`text-base md:text-xl font-medium transition-all duration-500 text-custom-gray w-fit ${
                  openIndex === index && "text-custom-second font-semibold"
                }`}
              ></h3>
              <TfiArrowCircleRight
                size={30}
                className={`transition-all duration-300  ${
                  openIndex === index
                    ? "rotate-90 text-custom-second"
                    : "text-custom-gray"
                }`}
              />
            </div>
            <div
              ref={(el) => (contentRefs.current[index] = el)}
              className="text-start max-h-0 transition-max-height duration-500 ease-in-out w-full overflow-auto pr-6"
            >
              {isMathJaxContent(item.answer) ? (
                <MathJax dynamic inline>
                  {item.answer}
                </MathJax>
              ) : (
                <div dangerouslySetInnerHTML={{ __html: item.answer }} />
              )}
            </div>
          </div>
        ))}
      </div>
    </MathJaxContext>
  );
};

export default FaqItem;

![image](https://github.com/user-attachments/assets/1fca0d31-c494-4aa4-a900-3cc033f9413f)

**Comment by fast-reflexes** [comment]
Hi!

I suggest you read the docs on how to use this library: https://github.com/fast-reflexes/better-react-mathjax?tab=readme-ov-file#usage

You're doing two things very wrong in the above example:
* You're not even using the `MathJaxContext` and `MathJax` components, simply importing them does not automatically make you use them.
* You're actually attempting to use Mathjax the regular Javascript way, you should EITHER use `better-react-mathjax` OR you do it the traditional way, not both.

Have a look at the docs referenced above, there are plenty of examples too.
