### ISSUE TITLE
Support for MathJax 4

### ISSUE THREAD

**Issue by chinaowl** [fast-reflexes/better-react-mathjax#72]
Hello! I was wondering if there are plans to add MathJax 4 as an option? It's currently in beta: https://github.com/mathjax/mathjax/releases

I am mostly interested in the automatic line breaking feature.

**Comment by fast-reflexes** [comment]
Umm ... since it is still in beta, it's not a choice that is obvious ... I would of course introduce support for this but ... I can't find any documentation on it .. can you point me to some docs? Is it configurable in the same way as Mathjax 3 or are there a lot of breaking changes?

**Comment by chinaowl** [comment]
Unfortunately I can't find anything either, other than what's hinted at in the release notes. So I guess it might be too soon.

Thank you for the quick reply!

**Comment by fast-reflexes** [comment]
Will try to add v4 once it has been released and the support / docs is a bit more elaborate :) Closing for now!

**Comment by dmahely-alef** [comment]
Hello all! Mathjax v4 has been publicly released in August 2025. Here is the [migration guide](https://docs.mathjax.org/en/latest/upgrading/v3.html) and list of [breaking changes](https://docs.mathjax.org/en/latest/upgrading/whats-new-4.0/breaking.html#v4-breaking-changes).

**Comment by devkat** [comment]
@fast-reflexes, are there any news regarding MathJax 4 update? TIA!

**Comment by fast-reflexes** [comment]
Nope, it's being worked on but not too much time on my hands right now, but I got a branch going :)

**Comment by fast-reflexes** [comment]
Version :tada: 2.4.0-beta-1 is out with support for Mathjax 4. Please let me know if stuff doesn't work as it should :)

**Comment by fast-reflexes** [comment]
Implemented and released in v 3.0.0
